apps/zaspalavra/lib/zaspalavra_web/router.ex
defmodule ZaspalavraWeb.Router do
  use ZaspalavraWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", ZaspalavraWeb do
    pipe_through :browser # Use the default browser stack

    get "/poll/:id", PageController, :show
    get "/", PageController, :index

    post "/approve/:id", PageController, :approve
    post "/reject/:id", PageController, :reject

    resources "/words", WordController

    get "/ranking", RankingController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", ZaspalavraWeb do
  #   pipe_through :api
  # end
end

apps/zaspalavra/lib/zaspalavra/application.ex
defmodule Zaspalavra.Application do
  use Application

  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  def start(_type, _args) do
    import Supervisor.Spec

    # Define workers and child supervisors to be supervised
    children = [
      # Start the Ecto repository
      supervisor(Zaspalavra.Repo, []),
      # Start the endpoint when the application starts
      supervisor(ZaspalavraWeb.Endpoint, []),
      # Start your own worker by calling: Zaspalavra.Worker.start_link(arg1, arg2, arg3)
      # worker(Zaspalavra.Worker, [arg1, arg2, arg3]),
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Zaspalavra.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    ZaspalavraWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

apps/zaspalavra/lib/zaspalavra/dictionary.ex
defmodule Zaspalavra.Dictionary do

  def definition_url(word), do: "https://pt.wiktionary.org/wiki/#{word}"

end

apps/zaspalavra/lib/zaspalavra/ranking.ex
defmodule Zaspalavra.Ranking do
  import Ecto.Query

  alias Zaspalavra.Words.Word
  alias Zaspalavra.Repo

  def take_best(count) do
    positions = Range.new(1, count)
    |> Enum.map(&(%{position: &1}))

    query(count)
    |> Repo.all()
    |> Enum.map(&Word.fill_in_dynamic_fields/1)
    |> Enum.map(&Map.from_struct/1)
    |> Enum.zip(positions)
    |> Enum.map(&merge/1)
  end

  defp query(count) do
    from w in Word, order_by: [desc: w.votes], limit: ^count
  end

  defp merge({word, position}), do: Map.merge(word, position)
end

apps/zaspalavra/lib/zaspalavra/repo.ex
defmodule Zaspalavra.Repo do
  use Ecto.Repo, otp_app: :zaspalavra

  @doc """
  Dynamically loads the repository url from the
  DATABASE_URL environment variable.
  """
  def init(_, opts) do
    {:ok, Keyword.put(opts, :url, System.get_env("DATABASE_URL"))}
  end
end

apps/zaspalavra/lib/zaspalavra/words/word.ex
defmodule Zaspalavra.Words.Word do
  use Ecto.Schema
  import Ecto.Changeset


  schema "words" do
    field :prefix, :string
    field :votes, :integer
    field :word, :string

    field :display_word, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(word, attrs) do
    word
    |> cast(attrs, [:prefix, :word, :votes])
    |> validate_required([:prefix, :word, :votes])
  end

  def fill_in_dynamic_fields(word) do
    %__MODULE__{word | display_word: word.prefix <> word.word}
  end
end

apps/zaspalavra/lib/zaspalavra/words/words.ex
defmodule Zaspalavra.Words do
  import Ecto.Query, warn: false

  alias Ecto.Adapters.SQL
  alias Zaspalavra.Repo
  alias Zaspalavra.Words.Word

  def list_words do
    Repo.all(Word)
  end

  def get_word!(id) do
    Repo.get(Word, id)
    |> prepare_result()
  end

  defp prepare_result(nil), do: {:not_found}
  defp prepare_result(word), do: {:ok, Word.fill_in_dynamic_fields(word)}

  def get_random_id() do
    sql = ~s[SELECT id FROM words ORDER BY RAND() LIMIT 1]
    %{rows: [[random_id]]} = SQL.query!(Repo, sql, [])
    random_id
    |> Kernel.trunc()
  end

  def approve(id) do
    sql = ~s[UPDATE words SET votes = votes + 1 WHERE id = ?]
    {result, _} = SQL.query(Repo, sql, [id])
    result
  end

  def reject(id) do
    sql = ~s[UPDATE words SET votes = votes - 1 WHERE id = ?]
    {result, _} = SQL.query(Repo, sql, [id])
    result
  end

  def create_word(attrs \\ %{}) do
    %Word{}
    |> Word.changeset(attrs)
    |> Repo.insert()
  end

  def update_word(%Word{} = word, attrs) do
    word
    |> Word.changeset(attrs)
    |> Repo.update()
  end

  def delete_word(%Word{} = word) do
    Repo.delete(word)
  end

  def change_word(%Word{} = word) do
    Word.changeset(word, %{})
  end
end

apps/zaspalavra/lib/zaspalavra_web/controllers/page_controller.ex
defmodule ZaspalavraWeb.PageController do
  use ZaspalavraWeb, :controller

  alias Zaspalavra.Words
  alias Zaspalavra.Dictionary

  def show(conn, %{"id" => id}) do
    word = Words.get_word!(id)
    show_word(conn, word)
  end

  def index(conn, _params) do
    random_id = Words.get_random_id()
    conn
    |> redirect(to: page_path(conn, :show, random_id))
  end

  def approve(conn, %{"id" => word_id}) do
    :ok = Words.approve(word_id)

    conn
    |> put_flash(:info, "Voto recebido")
    |> redirect to: "/"
  end

  def reject(conn, %{"id" => word_id}) do
    :ok = Words.reject(word_id)

    conn
    |> put_flash(:info, "Voto recebido")
    |> redirect to: "/"
  end

  defp show_word(conn, {:not_found}) do
    conn
    |> put_status(:not_found)
    |> render(ZaspalavraWeb.ErrorView, "404.html")
  end

  defp show_word(conn, {:ok, word}) do
    definition_url = Dictionary.definition_url(word.word)
    render conn, "index.html", word: word, definition_url: definition_url
  end
end

apps/zaspalavra/lib/zaspalavra_web/controllers/ranking_controller.ex
defmodule ZaspalavraWeb.RankingController do
  use ZaspalavraWeb, :controller

  alias Zaspalavra.Ranking

  def index(conn, _) do
    words = Ranking.take_best(10)
    render conn, "index.html", words: words
  end
end

apps/zaspalavra/lib/zaspalavra_web/controllers/word_controller.ex
defmodule ZaspalavraWeb.WordController do
  use ZaspalavraWeb, :controller

  alias Zaspalavra.Words
  alias Zaspalavra.Words.Word

  def index(conn, _params) do
    words = Words.list_words()
    render(conn, "index.html", words: words)
  end

  def new(conn, _params) do
    changeset = Words.change_word(%Word{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"word" => word_params}) do
    case Words.create_word(word_params) do
      {:ok, word} ->
        conn
        |> put_flash(:info, "Word created successfully.")
        |> redirect(to: word_path(conn, :show, word))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    word = Words.get_word!(id)
    render(conn, "show.html", word: word)
  end

  def edit(conn, %{"id" => id}) do
    word = Words.get_word!(id)
    changeset = Words.change_word(word)
    render(conn, "edit.html", word: word, changeset: changeset)
  end

  def update(conn, %{"id" => id, "word" => word_params}) do
    word = Words.get_word!(id)

    case Words.update_word(word, word_params) do
      {:ok, word} ->
        conn
        |> put_flash(:info, "Word updated successfully.")
        |> redirect(to: word_path(conn, :show, word))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", word: word, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    word = Words.get_word!(id)
    {:ok, _word} = Words.delete_word(word)

    conn
    |> put_flash(:info, "Word deleted successfully.")
    |> redirect(to: word_path(conn, :index))
  end
end

apps/zaspalavra/lib/zaspalavra_web/views/error_view.ex
defmodule ZaspalavraWeb.ErrorView do
  use ZaspalavraWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

apps/zaspalavra/lib/zaspalavra_web/views/layout_view.ex
defmodule ZaspalavraWeb.LayoutView do
  use ZaspalavraWeb, :view
end

apps/zaspalavra/lib/zaspalavra_web/views/page_view.ex
defmodule ZaspalavraWeb.PageView do
  use ZaspalavraWeb, :view
end

apps/zaspalavra/lib/zaspalavra_web/views/ranking_view.ex
defmodule ZaspalavraWeb.RankingView do
  use ZaspalavraWeb, :view
end

apps/zaspalavra/lib/zaspalavra_web/views/word_view.ex
defmodule ZaspalavraWeb.WordView do
  use ZaspalavraWeb, :view
end

apps/zaspalavra/lib/zaspalavra_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Zaspalavra!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

apps/zaspalavra/lib/zaspalavra_web/templates/page/index.html.eex
<h1 class="word"><%= @word.display_word %></h1>

<div class="col-xs-6">
  <%= button("✔ Aprovada", to: page_path(@conn, :approve, @word.id), method: :post, class: "btn btn-lg btn-success") %>
</div>

<div class="col-xs-6">
  <%= button("✘ Reprovada", to: page_path(@conn, :reject, @word.id), method: :post, class: "btn btn-lg btn-danger") %>
</div>

<div class="col-xs-12 definition-link">
  <p>Ver definição de <%= link(@word.display_word, to: @definition_url, target: "_blank") %></p>
</div>

<div class="col-xs-12 definition-link">
  <p><%= link("Ranking", to: ranking_path(@conn, :index), target: "_blank") %></p>
</div>

apps/zaspalavra/lib/zaspalavra_web/templates/ranking/index.html.eex
<h1>Ranking</h1>

<table class="table">
  <tbody>
    <%= for word <- @words do %>
      <tr>
        <td><%= word.position %></td>
        <td><%= word.display_word %></td>
        <td><%= word.votes %></td>
      </tr>
    <% end %>
  </tbody>
</table>

apps/zaspalavra/lib/zaspalavra_web/templates/word/edit.html.eex
<h2>Edit Word</h2>

<%= render "form.html", Map.put(assigns, :action, word_path(@conn, :update, @word)) %>

<span><%= link "Back", to: word_path(@conn, :index) %></span>

apps/zaspalavra/lib/zaspalavra_web/templates/word/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :prefix, class: "control-label" %>
    <%= text_input f, :prefix, class: "form-control" %>
    <%= error_tag f, :prefix %>
  </div>

  <div class="form-group">
    <%= label f, :word, class: "control-label" %>
    <%= text_input f, :word, class: "form-control" %>
    <%= error_tag f, :word %>
  </div>

  <div class="form-group">
    <%= label f, :votes, class: "control-label" %>
    <%= number_input f, :votes, class: "form-control" %>
    <%= error_tag f, :votes %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

apps/zaspalavra/lib/zaspalavra_web/templates/word/index.html.eex
<h2>Listing Words</h2>

<table class="table">
  <thead>
    <tr>
      <th>Prefix</th>
      <th>Word</th>
      <th>Votes</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for word <- @words do %>
    <tr>
      <td><%= word.prefix %></td>
      <td><%= word.word %></td>
      <td><%= word.votes %></td>

      <td class="text-right">
        <span><%= link "Show", to: word_path(@conn, :show, word), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: word_path(@conn, :edit, word), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: word_path(@conn, :delete, word), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Word", to: word_path(@conn, :new) %></span>

apps/zaspalavra/lib/zaspalavra_web/templates/word/new.html.eex
<h2>New Word</h2>

<%= render "form.html", Map.put(assigns, :action, word_path(@conn, :create)) %>

<span><%= link "Back", to: word_path(@conn, :index) %></span>

apps/zaspalavra/lib/zaspalavra_web/templates/word/show.html.eex
<h2>Show Word</h2>

<ul>

  <li>
    <strong>Prefix:</strong>
    <%= @word.prefix %>
  </li>

  <li>
    <strong>Word:</strong>
    <%= @word.word %>
  </li>

  <li>
    <strong>Votes:</strong>
    <%= @word.votes %>
  </li>

</ul>

<span><%= link "Edit", to: word_path(@conn, :edit, @word) %></span>
<span><%= link "Back", to: word_path(@conn, :index) %></span>